"""Sandcastle runner — invoke ``npx sandcastle`` as a subprocess.

The runner generates ``.sandcastle/main.ts`` and ``.sandcastle/prompt.md``
in the target directory, then runs ``npx tsx .sandcastle/main.ts`` and
parses the trailing JSON summary line that Sandcastle emits on exit.

Tests mock the subprocess via ``runner_options['_subprocess_factory']``;
the integration smoke test exercises the real path.
"""

from __future__ import annotations

import asyncio
import json
import shutil
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from swarmlord.core.errors import RunnerError
from swarmlord.runners.base import RunRequest, RunResult

# TODO(v1-smoke): the @anthropic/sandcastle import below is a placeholder.
# Verify the actual published Sandcastle package name on the first real
# integration smoke test and update the import + the API surface (the
# Sandcastle constructor and run() shape) to match. Until that smoke test
# runs, this template is unverified scaffolding.
_DEFAULT_MAIN_TS = """// Generated by SwarmLord. Do not edit by hand.
import { Sandcastle } from "@anthropic/sandcastle";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const prompt = readFileSync(join(__dirname, "prompt.md"), "utf-8");

const sandcastle = new Sandcastle({
  claudeCode: {
    model: process.env.SANDCASTLE_MODEL ?? "claude-sonnet-4-6",
  },
});

const result = await sandcastle.run({
  prompt,
  maxTurns: Number(process.env.SANDCASTLE_MAX_TURNS ?? 20),
});

console.log("__SANDCASTLE_SUMMARY__" + JSON.stringify({
  exitCode: result.exitCode ?? 0,
  completionSignal: result.completionSignal ?? null,
  commits: result.commits ?? [],
  transcriptPath: result.transcriptPath ?? null,
}));
"""


class SandcastleDockerRunner:
    """Sandcastle subprocess runner."""

    name: str = "sandcastle-docker"

    def can_handle(self, profile: str) -> bool:
        return profile == self.name

    async def run(self, request: RunRequest) -> RunResult:
        target = request.packet_root
        sandcastle_dir = target / ".sandcastle"
        sandcastle_dir.mkdir(parents=True, exist_ok=True)
        prompt_path = sandcastle_dir / "prompt.md"
        prompt_path.write_text(request.rendered_prompt, encoding="utf-8")
        main_ts = sandcastle_dir / "main.ts"
        if not main_ts.is_file() or request.runner_options.get("regenerate_main_ts"):
            main_ts.write_text(_DEFAULT_MAIN_TS, encoding="utf-8")

        npx = request.runner_options.get("npx_binary") or shutil.which("npx") or "npx"
        cmd: list[str] = [npx, "tsx", str(main_ts.relative_to(target))]
        env_overrides = {
            "SANDCASTLE_MAX_TURNS": str(request.workflow.agent.max_turns),
        }

        started = datetime.now(UTC)
        rc, stdout, stderr = await self._run_subprocess(
            cmd,
            cwd=target,
            env_overrides=env_overrides,
            options=request.runner_options,
        )
        ended = datetime.now(UTC)

        summary = _parse_summary(stdout) or _parse_summary(stderr)
        completion_signal = (summary or {}).get("completionSignal")
        commits = (summary or {}).get("commits") or []
        transcript_raw = (summary or {}).get("transcriptPath")
        transcript_path = Path(transcript_raw) if transcript_raw else None

        if summary is None and rc == 0:
            raise RunnerError("sandcastle completed with exit 0 but no summary line was found")

        return RunResult(
            runner=self.name,
            started_at=started,
            ended_at=ended,
            exit_code=rc,
            completion_signal_seen=completion_signal,
            log_path=None,
            transcript_path=transcript_path,
            commits=list(commits),
        )

    async def _run_subprocess(
        self,
        cmd: list[str],
        *,
        cwd: Path,
        env_overrides: dict[str, str],
        options: dict[str, Any],
    ) -> tuple[int, str, str]:
        injected = options.get("_subprocess_factory")
        if injected is not None:
            result: tuple[int, str, str] = await injected(cmd, cwd, env_overrides)
            return result
        import os

        env = {**os.environ, **env_overrides}
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            cwd=str(cwd),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )
        stdout_b, stderr_b = await proc.communicate()
        return (
            proc.returncode if proc.returncode is not None else -1,
            stdout_b.decode("utf-8", errors="replace"),
            stderr_b.decode("utf-8", errors="replace"),
        )


def _parse_summary(text: str) -> dict[str, Any] | None:
    """Extract the trailing ``__SANDCASTLE_SUMMARY__{json}`` line from output."""
    for line in reversed(text.splitlines()):
        marker = "__SANDCASTLE_SUMMARY__"
        idx = line.find(marker)
        if idx == -1:
            continue
        try:
            payload = json.loads(line[idx + len(marker) :])
        except json.JSONDecodeError:
            return None
        if isinstance(payload, dict):
            return payload
        return None
    return None
